;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hippie-expand-no-case-fold
        html-wrap-in-tag
        js2-beginning-of-line
        js2-end-of-line
        js2-insert-and-indent
        js2-mode-show-node
        js2r-inline-var
        js2r-var-to-this
        kill-region-or-backward-word
        magit-stage-item
        markdown-enter-key
        mouse-minor-mode-menu
        move-line-down
        move-line-up
        new-line-above
        org-delete-backward-char
        org-delete-char
        org-metaleft
        org-metaright
        org-self-insert-command
        org-shiftright
        orgtbl-self-insert-command
        quoted-insert
        save-region-or-current-line
        sgml-delete-tag
        sgml-slash
        slime-space
        wrap-region-trigger
        yank-indented
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        eval-buffer
        mouse-drag-mode-line
        new-line-below
        wgrep-change-to-wgrep-mode
        ))
